### ISSUE TITLE
unexpected token import

### ISSUE THREAD

**Issue by wjzheng** [jy0529/vite-plugin-dynamic-publicpath#1]
This plugin works well on modern browser, but occur an exception on older browser ,such as Android <=6，maybe the follow codes need to fix.
![image](https://user-images.githubusercontent.com/3063693/124695802-81823200-df16-11eb-8aab-ab77aa67f5c3.png)
--error--
![image](https://user-images.githubusercontent.com/3063693/124699302-1e47ce00-df1d-11eb-90de-aff764521842.png)
--browser--
![image](https://user-images.githubusercontent.com/3063693/124699406-4f280300-df1d-11eb-8036-a713062722a7.png)

**Comment by jy0529** [comment]
Fixed in 1.0.1 version, you can look [the legacy browser demo](https://github.com/jy0529/vite-plugin-dynamic-publicpath/tree/main/examples/legacy-demo).

But I have not Android 6.0 system's phone , if you test it failure, please tell me.

**Comment by wjzheng** [comment]
It's ok now, thank you!
