### ISSUE TITLE
preload path is preprended with basepath

### ISSUE THREAD

**Issue by chessydk** [jy0529/vite-plugin-dynamic-publicpath#6]
Hey - cool you've implemented the dynamic asset loading. Works fine for me for actual import, but for preload link it prepends the basepath.

I have
        `window.__dynamicImportPreload__ = function(preloads) {
            return preloads.map(preload => 'https://cdne-web-site-prod-kvadrat.azureedge.net/' + preload);
        `}

Which gives me this preload path (notice it does not start with my CDN url):

![image](https://user-images.githubusercontent.com/1286704/146013649-2883c1fb-fb77-4779-be59-c0990bb25ca1.png)

Also - I need to put a slash after the cdn - otherwise its not separated from the 'assets/xxx' part - thats not the case for the imports.

**Comment by jy0529** [comment]
it's vite added the base path build-in, you can set the base empty, see #3 .
